singleQuote: false
semi: true
printWidth: 100
trailingComma: none
useTabs: true
quoteProps: "double"
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
